### PR TITLE
Br vignettes

### PR DESCRIPTION
**Pull request by BrentWHR**

### CODE REVIEW

**Comment by BrentWHR** [comment]
@gerardhros What do you think of the vignette now? Let me know if you want me to make any adjustments.
I plan to complete the section on nematodes once that function is further developed.

**Comment by BrentWHR** [comment]
There are some citations in the vignette text but there is no reference list in the text.

**Comment by gerardhros** [comment]
@BrentWHR ,

This need to be added:
add vb crumbleability and stability
add vb soil compaction
add vb water retention
add vb disease resistance irt os
add vb for crop rotation and som balance?
add a figure illustrating the integration step to a score
add legend PMN inside the figure

table of field properties to calculate N leaching... graag uitschrijven

it might be interesting to add some of the lollipop figures for a soil as illustration? Similar you did for the pdf-reports (lollipop per aggregated soil type). use default ggplot for that.

This is not correct any more: "Currently, the soil functions are weighted on the level of function category (35% for chemical, 35% for physical, and 20% for biological indicators) and 10% for management. " Zie de code voor de integratie van scores.

**Comment by gerardhros** [comment]
citations...see the original factsheets for the original references. you might add these to the documentation.

**Comment by BrentWHR** [comment]
@gerardhros examples, citations, uniform colouring of plots, and graphic explanation of aggregation have been added.

**Comment by BrentWHR** [comment]
In 3c407ad a figure with relations between soil functions and the indicators is produced but metling the data going into the figure needs to be improved. The inputd dt now has indicator and function values for each function per function (instead of 101 rows per function/indicator there are 1919, corresponding with 20 indicators). Also, the soil function values do not all have the proper range for clear illustration of the evaluation.

**Comment by gerardhros** [comment]
i merged dev first in this branch. 
due to the update, i need to update quite some parts of the vignettes.
i will make an issue for the aggregation score. i expect that the variance of the obi score is declining when no weighing correction is applied. is that also the case? the code can in a few sections be improved in data.table style.

**Comment by BrentWHR** [comment]
> 
> 
> i will make an issue for the aggregation score. i expect that the variance of the obi score is declining when no weighing correction is applied. is that also the case? the code can in a few sections be improved in data.table style.

This is not the case.
The illustration in the score aggregation vignette indicates that without any correction factor, variance of total scores is slightly higher compared to applying log correction factors.
I too, expect higher variance when applying correction factors. Just to be sure; are you refering to variance in scores or to variance in indicators/input?

**Pull request merged**
